In [1]:
import random
import numpy as np

In [18]:
def Partition(arr, low, high):
  pivot = arr[high]
  i = low
  j = high-1

  while i<j:
    while i<high and arr[i] < pivot:
      i += 1
    while j>low and arr[j] > pivot:
      j -= 1

    if i < j:
      arr[i], arr[j] = arr[j], arr[i]
    
  if arr[i] > pivot:
    arr[i], arr[high] = arr[high], arr[i]
  
  return i


In [26]:
def QuickSort(arr, low=0, high=None):
  if not high:
    high = len(arr)-1
  if not low<high:
    return None
  pivot_index = Partition(arr, low, high)
  QuickSort(arr, low, pivot_index-1)
  QuickSort(arr, pivot_index+1, high)

In [35]:
a = np.random.randint(-100, 300, 20)
a

array([-35,  89, 288,  19, -63, 228, -75, -92,  93, 289, -91, 264,  28,
       246,  32, 279,  68, 189, 108,  83])

In [36]:
b = np.sort(a)
b

array([-92, -91, -75, -63, -35,  19,  28,  32,  68,  83,  89,  93, 108,
       189, 228, 246, 264, 279, 288, 289])

In [37]:
QuickSort(a,0, len(a)-1)

In [38]:

a

array([-92, -91, -75, -63, -35,  19,  28,  32,  68,  83,  89,  93, 108,
       189, 228, 246, 264, 279, 288, 289])

In [21]:
pivot_ind = Partition(a, 0, len(a)-1)
pivot_ind

2

In [22]:
a

array([-4, -1, 12, 19, 19, 17, 26])